### ISSUE TITLE
环境变量

### ISSUE THREAD

**Issue by songzhenjin** [kkfive/kkadmin-open#2]
请问VITE_GLOB_UPLOAD_URL和VITE_GLOB_UPLOAD_TOKEN这两个变量从哪里找到

**Comment by fmkli** [comment]
这两个分别对应图床上传的api和认证token，仅限兰空图床程序

**Comment by fmkli** [comment]
好像吧emmmm

**Comment by kkfive** [comment]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/82026204/185521748-df168109-b00e-4600-bc85-9a190d06563c.png">
