### ISSUE TITLE
code: 404

### ISSUE THREAD

**Issue by weekdaycare** [kkfive/kkadmin-open#3]
您好，我在部署完成后碰到了下面的状况，请问有什么解决方法呢？

![image](https://user-images.githubusercontent.com/63026074/194032239-c7425190-e62f-4a6b-8d3f-b8894540787c.png)

> 下面是kkapi的截图
>
> ![image](https://user-images.githubusercontent.com/63026074/194031790-b325a71b-c73c-4398-8c82-c3c0e71c8ec0.png)

本人才疏学浅，恳请大佬帮忙解答

**Comment by kkfive** [comment]
地址呢？

**Comment by weekdaycare** [comment]
kkapi： https://kkapi-open-two.vercel.app

kkadmin： https://kkadmin-open-nine.vercel.app

**Comment by kkfive** [comment]
https://kkapi.js.org/reference/kkadmin/environment.html

**Comment by weekdaycare** [comment]
环境变量应该是没有问题的

![image](https://user-images.githubusercontent.com/63026074/194242443-6adb96d1-e167-4f07-90b8-977fc049a434.png)

**Comment by kkfive** [comment]
重新部署下试试呢？

因为我看到你提供的地址中 配置文件中不包含环境变量的配置

**Comment by weekdaycare** [comment]
重新部署了似乎并没有起作用

![image](https://user-images.githubusercontent.com/63026074/194271898-b46ee8de-fd14-440a-b4c1-bfa6ba2009b1.png)

**Comment by kkfive** [comment]
https://kkadmin-open-nine.vercel.app/_app.config.js?v=2.8.0-1664959750510

这个配置文件的里都没有你设置的那些环境变量

**Comment by weekdaycare** [comment]
问题已解决

我刚刚去您的kk-admin网站看了一下

https://kkadmin-open.vercel.app/_app.config.js?v=2.8.0-1664959750510 和我的似乎一样，均是这个代码

```
window.__PRODUCTION____APP__CONF__={"VITE_GLOB_API_URL_PREFIX":"/api"};Object.freeze(window.__PRODUCTION____APP__CONF__);Object.defineProperty(window,"__PRODUCTION____APP__CONF__",{configurable:false,writable:false,});
```

然后我看vercel目前是支持node16的，于是我就想着能否跳过action直接在vercel上编译？

于是我把vercel部署分支改为 `master` ，然后将vercel的部署命令改为了下面的值

![image](https://user-images.githubusercontent.com/63026074/194575032-289b2ce4-eea9-4b94-9fd4-52e0a9d782ae.png)

再次重新部署，部署成功后访问就没有问题了

![image](https://user-images.githubusercontent.com/63026074/194575582-1abe6bcc-f092-48c6-a625-a12c390bcb24.png)
