### ISSUE TITLE
初次登陆输入初始化账号及密码，报错Request failed with status code 401

### ISSUE THREAD

**Issue by lpy716** [kkfive/kkadmin-open#5]
作者大大您好！我按照教程部署完成后，在最后的登录界面输入初始化账号及密码，结果报错401。恳请赐教，非常感谢！

此为本人[kkapi](https://kkapi-open-psi.vercel.app/)和[kkadmin](https://kkadmin-open-theta.vercel.app/)地址。关于环境变量设置，自己确保是与[教程](https://kkapi.js.org/reference/kkadmin/environment.html)保持一致。（特别是我注意到教程上实际用的去不图床，而不是兰空图床，因此token填的是在7bu那边创建的，而不是lsky的）

此外，我还参照了[#3](https://github.com/kkfive/kkadmin-open/issues/3)题主摸索出的做法尝试修改，结果报错`error Couldn't find a package.json file in "/vercel/path0"`，遂放弃。

**Comment by yooloop** [comment]
> 作者大大您好！我按照教程部署完成后，在最后的登录界面输入初始化账号及密码，结果报错401。恳请赐教，非常感谢！
> 
> 此为本人[kkapi](https://kkapi-open-psi.vercel.app/)和[kkadmin](https://kkadmin-open-theta.vercel.app/)地址。关于环境变量设置，自己确保是与[教程](https://kkapi.js.org/reference/kkadmin/environment.html)保持一致。（特别是我注意到教程上实际用的去不图床，而不是兰空图床，因此token填的是在7bu那边创建的，而不是lsky的）
> 
> 此外，我还参照了[#3](https://github.com/kkfive/kkadmin-open/issues/3)题主摸索出的做法尝试修改，结果报错`error Couldn't find a package.json file in "/vercel/path0"`，遂放弃。
你好，请问你解决了吗？

**Comment by lpy716** [comment]
已自行解决问题。

401报错其实指没有查到我原本已成功开设的初始账户。回过头检查，发现自己在根据教程配置kkapi后台时，到Actions的执行这里就失败了（具体是”6.推送到vercel分支“这一步，报错`fatal: unable to access 'https://github.com/lpy716/kkadmin-open.git/'`，它上面提示问题出在了GITHUB_TOKEN配置上）。根据提示，打开仓库的Settings-Actions-General，把Workflow permissions的选项从”Read repository contents and packages permissions“改为”Read and write permissions“。后面就一切顺利了。
